version: '3.4'

services:
  react-app:
    build: ./react-app
    container_name: ${APP_NAME}-react-app
    env_file:
      - .env
    volumes:
      - ./react-app/src:/react-app/src
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    ports:
      - ${REACT_APP_DEV_PORT}:${REACT_APP_DEV_PORT}
      - 9000:9000