version: '3.4'

services:
  react-app:
    build: ./react-app
    container_name: ${APP_NAME}-react-app
    env_file:
      - .env
    volumes:
      - ./react-app/cypress:/react-app/cypress
      - ./react-app/src:/react-app/src
    ports:
      - ${DEV_PORT}:3000
      - ${TEST_PORT}:9000