env:
  browser: true
  es2021: true
root: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
  projectFolderIgnoreList: ['**/cypress/**']
plugins:
  - react
  - '@typescript-eslint'
globals: {
  cy: true,
  Cypress: true
}
settings: {
  react: {
    version: detect
  }
}
ignorePatterns:
  - cypress/**/*  
rules: {
  'semi': 'off',
  'indent': 'off',
  'eol-last': ['error', 'never'],
  '@typescript-eslint/semi': ['error', 'always'],
  '@typescript-eslint/indent': ['error', 2],
  '@typescript-eslint/no-floating-promises': 0,
  '@typescript-eslint/strict-boolean-expressions': 0,
  '@typescript-eslint/triple-slash-reference': 0,
  '@typescript-eslint/explicit-function-return-type': 0,
  '@typescript-eslint/consistent-type-definitions': 0,
  '@typescript-eslint/return-await': 0,
  '@typescript-eslint/space-before-function-paren': 0,
  '@typescript-eslint/restrict-template-expressions': 0,
  'no-trailing-spaces': 'off',
  no-return-assign: 0,
  operator-linebreak: 0,
  react/jsx-tag-spacing: 2,
  react/prop-types: 0,
  react/display-name: 0,
}